# run install of python requirements
name: Automated Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Check if mkdocs build works
        run: mkdocs build

      - name: Store the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-site
          path: site

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-sftp:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Get the build artifacts
        uses: actions/download-artifact@v2
        with:
          name: mkdocs-site
          path: site

      - name: Inspect artifacts
        run: ls -R site